SELECT  TO_NUMBER(SUBSTR(START_DATE, 5, 2))    AS MONTH
     ,  CAR_ID
     ,  COUNT(CAR_ID)                          AS RECORDS
  FROM  (
            SELECT  TO_CHAR(START_DATE, 'YYYYMMDD')         AS START_DATE
                 ,  CAR_ID
                 ,  COUNT(CAR_ID) OVER(PARTITION BY CAR_ID) AS CAR_COUNT
              FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY
             WHERE  TO_CHAR(START_DATE, 'YYYYMMDD') BETWEEN '20220801' AND '20231031'
        )
 WHERE  CAR_COUNT >= 5
 GROUP BY SUBSTR(START_DATE, 5, 2), CAR_ID
 ORDER BY SUBSTR(START_DATE, 5, 2), CAR_ID DESC
;