SELECT  P.PRODUCT_ID
     ,  P.PRODUCT_NAME
     ,  P.PRICE * F.AMOUNT  AS TOTAL_SALES
  FROM  FOOD_PRODUCT    P
     ,  (
            SELECT  PRODUCT_ID
                 ,  SUM(AMOUNT) AS AMOUNT
              FROM  FOOD_ORDER
             WHERE  TO_CHAR(PRODUCE_DATE, 'YYYYMMDD') BETWEEN '20220501' AND '20220531'
             GROUP BY PRODUCT_ID

        )               F
 WHERE  P.PRODUCT_ID    = F.PRODUCT_ID
 ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID
;
